### ISSUE TITLE
Using the Watson dialog tutorial : asking questions / getting answers

### ISSUE THREAD

**Issue by PhilippeComte** [watson-developer-cloud/dialog-tool#26]
Hello 
I am going thru Watson Dialog tutorial and using the Watson Dialog tool on Bluemix and locally.
In the box **Work with Dialogs *_I  upload the file exercise 1 .
In  the box : *_Have a conversation **
There is a input box labelled **Type a response** (shouldn't it  be question ? )
I write : What type of toppings do you have ?  (as suggested)
the question is placed in the conversation box
but there is no answer showing up. 
Can you help me ? 
Many thanks .

**Comment by PhilippeComte** [comment]
I have solved the above part (issues with credentials) . Still struggling with the Dialog id

**Comment by nfriedly** [comment]
Hey sorry for the slow response, it's been a long week. 

I'm not sure about this one though - I'm not actually all that familiar with this app, I just jumped on the first issue because it sounded like something I could help with. 

For this question, though, I'd recommend posting it to [IBM DeveloperWorks](https://developer.ibm.com/answers/smart-spaces/25/watson.html) or [Stack Overflow](http://stackoverflow.com/questions/ask?tags=ibm-watson). (GH Issues are intended more for reporting verified actual bugs in the app whereas DW and SO are better places for "help me get it working" sort of questions.)

**Comment by PhilippeComte** [comment]
I have found the soulution for the dialog id : each xml file  when uploaded gets a dialog id .

**Comment by PhilippeComte** [comment]
I have found the soulution for the dialog id : each xml file when uploaded gets a dialog id .
Still curious to understand how the id is computed ...

**Comment by germanattanasio** [comment]
It's a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier)
